version: '3'
services:
  mychatapp:
    build:
      context: ../MyChatApp
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    # links:
    #   - mongodb
    #   - redis
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo
  redis:
    image: redis
